name: Run lints and tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit-openresty"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4

    - name: Install luacheck
      run: luarocks install luacheck

    - name: Install busted
      run: luarocks install busted

    - name: Run lints
      run: make lint

    - name: Run tests
      run: make test
